{
    "id": "problem_37",
    "description": "\n\nWhen attempting to access a value in a dict object, a KeyError is raised indicating that the key being accessed does not exist in the dict object. This error occurs when trying to access a key that has not been added to the dict object or when the key is of the wrong type.",
    "code": "my_dict = {\n    \"name\": \"John\",\n    \"age\": 30\n}\n\nprint(my_dict[\"height\"])",
    "tags": [
        "KeyError",
        "dict",
        "Easy"
    ]
}