{
    "id": "problem_144",
    "description": "\n\nWhen attempting to read a file containing a DefaultDict, a FileNotFoundError is raised due to the file not existing in the current directory. This indicates that the DefaultDict is not able to be read and the program will not be able to access the data stored in the Default",
    "code": "from collections import defaultdict \n\nd = defaultdict(list) \nd['a'].append(1) \nd['a'].append(2) \nd['b'].append(4) \n\nfor key, value in d.",
    "tags": [
        "FileNotFoundError",
        "DefaultDict",
        "Easy"
    ]
}