{
    "id": "problem_171",
    "description": "\n\nThe problem is a KeyError when attempting to index a numpy array. When trying to access an element in the array, the program throws a KeyError indicating that the specified key does not exist in the array.",
    "output": "Traceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\nIndexError: index 6 is out of bounds for axis 0 with size 5",
    "tags": [
        "KeyError",
        "numpy",
        "Medium"
    ]
}