{
    "id": "problem_156",
    "description": "\n\nWhen running UnitTesting on a program, an OverflowError is thrown due to the amount of data being processed exceeding the maximum capacity of the program's memory.",
    "output": "Traceback (most recent call last):\n  File \"<stdin>\", line 10, in <module>\n    def test_example(self):\nIndentationError: expected an indented block",
    "tags": [
        "OverflowError",
        "UnitTesting",
        "Medium"
    ]
}